CSP-551 Implemented Application Submitted workflow
SkillsFundingAgency/das-employer-aan-web pull request #25
Opened 2023-08-09 20:30 UTC by YuvrajPatil-DFE

2023-08-10 07:19 UTC, MarkFCain commented on src/SFA.DAS.Employer.Aan.Web/Models/Onboarding/CheckYourAnswersViewModel.cs
>      }
these fields being populated needs coverage

2023-08-10 08:18 UTC, YuvrajPatil-DFE commented on src/SFA.DAS.Employer.Aan.Web/Models/Onboarding/CheckYourAnswersViewModel.cs
>      }
These fields are covered

2023-08-14 12:33 UTC, DevenKShah commented on src/SFA.DAS.Employer.Aan.Web/Models/Onboarding/OnboardingSessionModel.cs
> +    public string Email { get; set; } = null!;
Do we need to store fullname and email? as this is derived from session anyway

2023-08-14 12:33 UTC, DevenKShah commented on src/SFA.DAS.Employer.Aan.Web/Controllers/Onboarding/PreviousEngagementController.cs
> +            sessionModel.EmployerDetails.Email = User.GetEmail();
I think this is unnecessary

2023-08-14 12:33 UTC, DevenKShah commented on src/SFA.DAS.Employer.Aan.Web.UnitTests/Controllers/Onboarding/PreviousEngagementControllerTests/PreviousEngagementControllerPostTests.cs
> +
How is this helping test anything? Where are the verifications for new properties?

2023-08-14 12:33 UTC, DevenKShah commented on src/SFA.DAS.Employer.Aan.Web/Controllers/Onboarding/CheckYourAnswersController.cs
> +    private CreateEmployerMemberRequest GenerateCreateEmployerMemberRequest(OnboardingSessionModel source, string employerAccountId)
Use `Populate` or `Get` instead of Generate

2023-08-14 12:33 UTC, DevenKShah commented on src/SFA.DAS.Employer.Aan.Web/Controllers/Onboarding/CheckYourAnswersController.cs
> +        request.Email = source.EmployerDetails.Email;
Why are we reading email from employer details, why is there email in employer details?

2023-08-14 12:33 UTC, DevenKShah requested changes
Remove orig files

2023-08-17 06:37 UTC, DevenKShah commented on src/SFA.DAS.Employer.Aan.Web.UnitTests/Validators/Onboarding/CheckYourAnswersSubmitModelValidatorTests.cs
> +    public void Validate_IsRegionConfirmationDone_When_Regions_IsSet_And_IsMultiRegionalOrganisation_IsSet_ErrorNoError(
Only `Validate_IsRegionConfirmationDone` was enough

2023-08-17 06:40 UTC, DevenKShah approved these changes

2023-08-17 08:08 UTC, merged