CSP-527 Employer Onboarding - Tell us what area of the country your organisation works in
SkillsFundingAgency/das-employer-aan-web pull request #9
Opened 2023-05-23 14:27 UTC by YuvrajPatil-DFE

2023-05-24 10:40 UTC, DevenKShah commented on src/SFA.DAS.Employer.Aan.Application/Services/RegionService.cs
> +        var sortedList = result.Regions.OrderBy(x => x.Ordering).ToList();
@YuvrajPatil-DFE Can you please confirm that we are not ordering in the inner api or outer api?

2023-05-24 10:43 UTC, DevenKShah commented on src/SFA.DAS.Employer.Aan.Web.UnitTests/Controllers/Onboarding/RegionsControllerTests/RegionsControllerGetTests.cs
> +        List<Region> regionList = new()
You could add this to the method argument so it can be generated automatically for you

2023-05-24 10:44 UTC, DevenKShah commented on src/SFA.DAS.Employer.Aan.Web.UnitTests/Controllers/Onboarding/RegionsControllerTests/RegionsControllerGetTests.cs
> +    [MoqAutoData]
Add `[Test]` attributes to all of the test methods.

2023-05-24 10:44 UTC, DevenKShah commented on src/SFA.DAS.Employer.Aan.Web.UnitTests/Controllers/Onboarding/RegionsControllerTests/RegionsControllerPostTests.cs
> +    [MoqAutoData]
Add `[Test]` attributes to all of the test methods.

2023-05-24 10:44 UTC, DevenKShah commented on src/SFA.DAS.Employer.Aan.Web.UnitTests/Controllers/Onboarding/TermsAndConditionsControllerTests/TermsAndConditionsControllerPostTests.cs
>      [MoqAutoData]
Add `[Test]` attributes to all of the test methods.

2023-05-24 10:47 UTC, DevenKShah commented on src/SFA.DAS.Employer.Aan.Web/Filters/RequiredSessionModelAttribute.cs
> +    private static readonly string[] controllersToByPass = new[] { nameof(BeforeYouStartController), nameof(TermsAndConditionsController), nameof(RegionsController) };
Remove this from here, you should have session at the post of T&Cs

2023-05-24 10:48 UTC, DevenKShah requested changes
You have wrongly added RegionsController in ByPass rule. Also your tests are missing Test attribute

2023-05-24 10:50 UTC, DevenKShah commented on src/SFA.DAS.Employer.Aan.Web.UnitTests/Models/OnboardingSessionModelTests.cs
> +    public void ClearProfileValue_Clears_ProfilesInOnboardingSessionModel(OnboardingSessionModel sut)
ClearProfileValue_ClearsValueForGiveProfile

2023-05-24 11:03 UTC, DevenKShah commented on src/SFA.DAS.Employer.Aan.Web/Models/Onboarding/RegionsViewModel.cs
> +public class RegionModel
This needs to be in separate file as it is directly referenced in the OnboardingSessionModel

2023-05-24 11:04 UTC, DevenKShah commented on src/SFA.DAS.Employer.Aan.Web/SFA.DAS.Employer.Aan.Web.csproj
> +    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
We are not using FluentValidation pieline so there is no need to reference `"FluentValidation.AspNetCore"`

2023-05-24 11:06 UTC, DevenKShah commented on src/SFA.DAS.Employer.Aan.Web/Controllers/Onboarding/RegionsController.cs
> +    public async Task<IActionResult> Get()
A cancellation token should be taken as parameter and passed down to handler

2023-05-24 11:06 UTC, DevenKShah commented on src/SFA.DAS.Employer.Aan.Web/Controllers/Onboarding/RegionsController.cs
> +    public async Task<IActionResult> Post(RegionsSubmitModel submitmodel)
A cancellation token should be taken as parameter and passed down to handler

2023-05-24 11:07 UTC, DevenKShah commented on src/SFA.DAS.Employer.Aan.Domain/Interfaces/IOuterApiClient.cs
> +
We need to add cancellation token in all the methods here and this should be passed down  from the controller

2023-05-24 11:32 UTC, YuvrajPatil-DFE commented on src/SFA.DAS.Employer.Aan.Web/SFA.DAS.Employer.Aan.Web.csproj
> +    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
We are using it, when the validator fails for then we add Modelstate to result as follows
 if (!result.IsValid)
        {
            result.AddToModelState(ModelState);
            return View(ViewPath, model);
        }

2023-05-24 16:16 UTC, DevenKShah commented on src/SFA.DAS.Employer.Aan.Web/SFA.DAS.Employer.Aan.Web.csproj
> +    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
Good to know

2023-05-24 16:30 UTC, DevenKShah submitted a review, later dismissed

2023-05-25 11:49 UTC, MarkFCain approved these changes

2023-05-31 10:49 UTC, MarkFCain approved these changes

2023-05-31 10:49 UTC, MarkFCain approved these changes

2023-05-31 10:49 UTC, MarkFCain approved these changes

2023-05-31 14:40 UTC, furqanagwan approved these changes

2023-05-31 14:41 UTC, debrr07 approved these changes

2023-05-31 14:42 UTC, merged